version: '3.8'
services:
  backend:
    build: ./backend
    image: test763/ecommerce-fullstack-ci-cd-backend:02
    ports:
      - "8000:8000"
    # environment:
    #   - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    image: test763/ecommerce-fullstack-ci-cd-frontend:02
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    restart: always
    depends_on:
      - backend
